import type {
  SupplyTaskRecordDateOption,
  SupplyTaskRecordDrawHistoryItem,
  SupplyTaskRecordInvite,
  SupplyTaskRecordRedemption,
  SupplyTaskRecordTimelineItem,
} from "../supply-task-record/types";

export const supplyUiLabRecordDates: SupplyTaskRecordDateOption[] = [
  { key: "2026-05-18", label: "今天", dateLabel: "05月18日", weekday: "星期一" },
  { key: "2026-05-17", label: "昨天", dateLabel: "05月17日", weekday: "星期日" },
  { key: "2026-05-16", label: "前天", dateLabel: "05月16日", weekday: "星期六" },
  { key: "2026-05-15", label: "3天前", dateLabel: "05月15日", weekday: "星期五" },
  { key: "2026-05-14", label: "4天前", dateLabel: "05月14日", weekday: "星期四" },
  { key: "2026-05-13", label: "5天前", dateLabel: "05月13日", weekday: "星期三" },
  { key: "2026-05-12", label: "6天前", dateLabel: "05月12日", weekday: "星期二" },
];

const rewardIcons = {
  coins: "/gamification/rewards/icons/coins_020.png",
  ticket: "/gamification/rewards/icons/task_reroll_coupon.png",
  coffee: "/gamification/rewards/icons/luckin_coffee_coupon.png",
} as const;

export const supplyUiLabRecordsByDate: Record<string, SupplyTaskRecordTimelineItem[]> = {
  "2026-05-18": [
    {
      id: "movement-task",
      time: "08:21",
      title: "运动任务",
      subtitle: "累计步数 >= 8000 步",
      category: "mainline",
      categoryLabel: "主线任务",
      categoryTone: "green",
      icon: { type: "text", value: "步", alt: "运动任务" },
      reward: { icon: "券", label: "抽奖券", amount: "x1" },
      status: "completed",
      statusLabel: "已完成",
    },
    {
      id: "hydration-task",
      time: "09:03",
      title: "喝水任务",
      subtitle: "累计饮水 >= 2000 ml",
      category: "mainline",
      categoryLabel: "主线任务",
      categoryTone: "green",
      icon: { type: "text", value: "水", alt: "喝水任务" },
      reward: { icon: "券", label: "抽奖券", amount: "x1" },
      status: "completed",
      statusLabel: "已完成",
    },
    {
      id: "social-task",
      time: "10:15",
      title: "社交任务",
      subtitle: "与队友互动 >= 1 次",
      category: "social",
      categoryLabel: "社交互动",
      categoryTone: "green",
      icon: { type: "text", value: "聊", alt: "社交任务" },
      reward: { icon: "券", label: "抽奖券", amount: "x1" },
      status: "completed",
      statusLabel: "已完成",
    },
    {
      id: "learning-task",
      time: "11:40",
      title: "学习任务",
      subtitle: "学习时长 >= 30 分钟",
      category: "mainline",
      categoryLabel: "主线任务",
      categoryTone: "green",
      icon: { type: "text", value: "学", alt: "学习任务" },
      reward: { icon: "券", label: "抽奖券", amount: "x1" },
      status: "completed",
      statusLabel: "已完成",
    },
    {
      id: "mainline-bonus",
      time: "12:02",
      title: "完成全部主线任务",
      subtitle: "获得一次补给抽卡机会",
      category: "reward",
      categoryLabel: "奖励领取",
      categoryTone: "orange",
      icon: { type: "image", value: rewardIcons.ticket, alt: "抽奖券" },
      reward: { icon: "券", label: "抽奖券", amount: "x1" },
      status: "claimed",
      statusLabel: "已领取",
    },
    {
      id: "draw-reward",
      time: "12:05",
      title: "在补给抽卡机中抽取",
      subtitle: "十连抽触发批次保底",
      category: "draw",
      categoryLabel: "抽卡奖励",
      categoryTone: "orange",
      icon: { type: "text", value: "抽", alt: "抽卡奖励" },
      reward: { icon: "饮", label: "运动饮料（R）", amount: "x1" },
      status: "claimed",
      statusLabel: "已领取",
    },
    {
      id: "streak-reward",
      time: "12:06",
      title: "连续打卡 18 天奖励",
      subtitle: "连胜奖励已入账",
      category: "system",
      categoryLabel: "系统奖励",
      categoryTone: "orange",
      icon: { type: "image", value: rewardIcons.coins, alt: "银子" },
      reward: { icon: "银", label: "银子", amount: "x100" },
      status: "claimed",
      statusLabel: "已领取",
    },
  ],
  "2026-05-17": [
    {
      id: "yesterday-social",
      time: "09:18",
      title: "完成队友互动",
      subtitle: "回应大力水手的运动提醒",
      category: "social",
      categoryLabel: "社交互动",
      categoryTone: "green",
      icon: { type: "text", value: "聊", alt: "社交互动" },
      reward: { icon: "银", label: "银子", amount: "x10" },
      status: "completed",
      statusLabel: "已完成",
    },
    {
      id: "yesterday-draw",
      time: "12:25",
      title: "完成一次单抽",
      subtitle: "消耗抽奖券 1",
      category: "draw",
      categoryLabel: "抽卡奖励",
      categoryTone: "orange",
      icon: { type: "text", value: "抽", alt: "抽卡奖励" },
      reward: { icon: "券", label: "任务换班券", amount: "x1" },
      status: "claimed",
      statusLabel: "已领取",
    },
    {
      id: "yesterday-coins",
      time: "21:12",
      title: "夜间打卡奖励",
      subtitle: "完成今日所有记录",
      category: "reward",
      categoryLabel: "奖励领取",
      categoryTone: "orange",
      icon: { type: "image", value: rewardIcons.coins, alt: "银子" },
      reward: { icon: "银", label: "银子", amount: "x20" },
      status: "claimed",
      statusLabel: "已领取",
    },
  ],
  "2026-05-16": [
    {
      id: "before-yesterday-walk",
      time: "08:44",
      title: "散步提醒完成",
      subtitle: "队友雷达邀请已回应",
      category: "social",
      categoryLabel: "社交互动",
      categoryTone: "green",
      icon: { type: "text", value: "走", alt: "散步提醒" },
      reward: { icon: "银", label: "银子", amount: "x10" },
      status: "completed",
      statusLabel: "已完成",
    },
  ],
  "2026-05-15": [
    {
      id: "three-days-draw",
      time: "20:30",
      title: "十连抽记录",
      subtitle: "批次保底未触发",
      category: "draw",
      categoryLabel: "抽卡奖励",
      categoryTone: "orange",
      icon: { type: "text", value: "抽", alt: "抽卡奖励" },
      reward: { icon: "咖", label: "瑞幸咖啡券", amount: "x1" },
      status: "claimed",
      statusLabel: "已领取",
    },
  ],
  "2026-05-14": [
    {
      id: "four-days-water",
      time: "10:02",
      title: "喝水任务",
      subtitle: "累计饮水 >= 2000 ml",
      category: "mainline",
      categoryLabel: "主线任务",
      categoryTone: "green",
      icon: { type: "text", value: "水", alt: "喝水任务" },
      reward: { icon: "券", label: "抽奖券", amount: "x1" },
      status: "completed",
      statusLabel: "已完成",
    },
  ],
  "2026-05-13": [],
  "2026-05-12": [
    {
      id: "six-days-redeem",
      time: "19:40",
      title: "申请真实福利兑换",
      subtitle: "咖啡兑换券进入管理员确认流程",
      category: "system",
      categoryLabel: "兑换记录",
      categoryTone: "orange",
      icon: { type: "image", value: rewardIcons.coffee, alt: "瑞幸咖啡券" },
      reward: { icon: "咖", label: "瑞幸咖啡券", amount: "x1" },
      status: "claimed",
      statusLabel: "已提交",
    },
  ],
};

export const supplyUiLabDrawHistory: SupplyTaskRecordDrawHistoryItem[] = [
  {
    id: "draw-ten-2026-05-18",
    drawType: "十连",
    time: "05月18日 12:05",
    ticketSpent: 10,
    guaranteeApplied: true,
    guaranteeLabel: "批次保底已触发",
    rewards: [
      { name: "任务换班券", quantityLabel: "x1", rarity: "R" },
      { name: "银子", quantityLabel: "x5", rarity: "N" },
      { name: "瑞幸咖啡券", quantityLabel: "x1", rarity: "SSR" },
    ],
  },
  {
    id: "draw-single-2026-05-17",
    drawType: "单抽",
    time: "05月17日 12:25",
    ticketSpent: 1,
    guaranteeApplied: false,
    guaranteeLabel: "批次保底未触发",
    rewards: [{ name: "任务换班券", quantityLabel: "x1", rarity: "R" }],
  },
  {
    id: "draw-ten-2026-05-15",
    drawType: "十连",
    time: "05月15日 20:30",
    ticketSpent: 10,
    guaranteeApplied: false,
    guaranteeLabel: "批次保底累计 7/10",
    rewards: [
      { name: "银子", quantityLabel: "x20", rarity: "N" },
      { name: "运动饮料", quantityLabel: "x1", rarity: "R" },
      { name: "瑞幸咖啡券", quantityLabel: "x1", rarity: "SSR" },
    ],
  },
];

export const supplyUiLabRadarInvites: SupplyTaskRecordInvite[] = [
  {
    id: "invite-sailor",
    avatar: "/avatars/male2.png",
    name: "大力水手",
    message: "邀请你互动",
    timeLabel: "今天 10:20",
    status: "pending",
    statusLabel: "待响应",
  },
  {
    id: "invite-deer",
    avatar: "/avatars/female1.png",
    name: "小鹿同学",
    message: "提醒你一起喝水",
    timeLabel: "今天 09:15",
    status: "pending",
    statusLabel: "待响应",
  },
  {
    id: "invite-runner",
    avatar: "/avatars/male3.png",
    name: "跑步阿斌",
    message: "约你晚上散步",
    timeLabel: "昨天 21:47",
    status: "pending",
    statusLabel: "待响应",
  },
  {
    id: "invite-coach",
    avatar: "/avatars/male1.png",
    name: "教练老周",
    message: "已回应你的拉伸邀请",
    timeLabel: "昨天 18:20",
    status: "responded",
    statusLabel: "已回应",
  },
  {
    id: "invite-expired",
    avatar: "/avatars/female2.png",
    name: "咖啡同学",
    message: "午后走路邀请已过期",
    timeLabel: "05月15日 14:00",
    status: "expired",
    statusLabel: "已过期",
  },
];

export const supplyUiLabRedemptions: SupplyTaskRecordRedemption[] = [
  {
    id: "coffee-processing",
    icon: rewardIcons.coffee,
    title: "瑞幸咖啡券",
    requestedAt: "申请时间：05-18 12:10",
    secondaryLabel: "预计完成：05-18 20:00",
    status: "processing",
    statusLabel: "兑换中",
  },
  {
    id: "coffee-completed",
    icon: rewardIcons.coffee,
    title: "瑞幸咖啡券",
    requestedAt: "申请时间：05-17 08:30",
    secondaryLabel: "完成时间：05-17 14:05",
    status: "completed",
    statusLabel: "已完成",
  },
  {
    id: "coffee-expired",
    icon: rewardIcons.coffee,
    title: "瑞幸咖啡券",
    requestedAt: "申请时间：05-12 19:40",
    secondaryLabel: "失效时间：05-14 19:40",
    status: "expired",
    statusLabel: "已失效",
  },
];

export const supplyUiLabRecordRules = [
  "日期 tab 展示最近 7 天，切换后只读取本地 recordsByDate。",
  "今日记录展示任务、奖励、抽卡和系统提示；无记录日期展示空状态。",
  "抽卡记录展示单抽、十连、消耗抽奖券和批次保底状态。",
  "队友雷达和兑换记录展示完整状态列表，但不响应真实社交邀请或真实兑换。",
];
