import type { ItemDefinition } from "./types";

export const ITEM_DEFINITIONS: ItemDefinition[] = [
  {
    id: "task_reroll_coupon",
    category: "task",
    name: "任务换班券",
    description: "把当天一个四维任务换成同维度另一张卡。",
    useTiming: "instant",
    effect: { type: "task_reroll", scope: "same_dimension" },
    stackable: true,
    maxUsePerUserPerDay: 1,
    requiresAdminConfirmation: false,
    enabled: true,
  },
  {
    id: "small_boost_coupon",
    category: "boost",
    name: "小暴击券",
    description: "当日真实健身打卡个人资产 1.5x，不影响赛季贡献。",
    useTiming: "today",
    effect: { type: "fitness_coin_multiplier", multiplier: 1.5 },
    stackable: false,
    maxUsePerUserPerDay: 1,
    requiresAdminConfirmation: false,
    enabled: true,
  },
  {
    id: "single_draw_guarantee_coupon",
    category: "lottery",
    name: "保底升级券",
    description: "下一次单抽至少不低于实用道具。",
    useTiming: "instant",
    effect: { type: "lottery_guarantee", minTier: "utility", appliesTo: "single" },
    stackable: true,
    requiresAdminConfirmation: false,
    enabled: true,
  },
  {
    id: "ticket_discount_90",
    category: "lottery",
    name: "九折购券卡",
    description: "今天十连补券享受一次 9 折。",
    useTiming: "instant",
    effect: { type: "ticket_discount", discountRate: 0.9 },
    stackable: false,
    maxUsePerUserPerDay: 1,
    requiresAdminConfirmation: false,
    enabled: true,
  },
  {
    id: "hydration_bonus",
    category: "boost",
    name: "补水加班费",
    description: "今天完成“把尿喝白”后额外获得少量银子。",
    useTiming: "today",
    effect: { type: "dimension_coin_bonus", dimensionKey: "hydration", amount: 5 },
    stackable: false,
    maxUsePerUserPerDay: 1,
    requiresAdminConfirmation: false,
    enabled: true,
  },
  {
    id: "movement_bonus",
    category: "boost",
    name: "站立补贴",
    description: "今天完成“把电充绿”后额外获得少量银子。",
    useTiming: "today",
    effect: { type: "dimension_coin_bonus", dimensionKey: "movement", amount: 5 },
    stackable: false,
    maxUsePerUserPerDay: 1,
    requiresAdminConfirmation: false,
    enabled: true,
  },
  {
    id: "double_niuma_coupon",
    category: "boost",
    name: "双倍牛马券",
    description: "当日真实健身打卡个人资产 2x，赛季贡献 2x。",
    useTiming: "today",
    effect: { type: "fitness_coin_and_season_multiplier", multiplier: 2 },
    stackable: false,
    maxUsePerUserPerWeek: 1,
    requiresAdminConfirmation: false,
    enabled: true,
  },
  {
    id: "season_sprint_coupon",
    category: "boost",
    name: "赛季冲刺券",
    description: "当日真实健身打卡赛季贡献 2x。",
    useTiming: "today",
    effect: { type: "fitness_season_multiplier", multiplier: 2 },
    stackable: false,
    maxUsePerUserPerWeek: 1,
    requiresAdminConfirmation: false,
    enabled: true,
  },
  {
    id: "coin_rich_coupon",
    category: "boost",
    name: "银子暴富券",
    description: "当日真实健身打卡个人资产 2x。",
    useTiming: "today",
    effect: { type: "fitness_coin_multiplier", multiplier: 2 },
    stackable: false,
    maxUsePerUserPerWeek: 1,
    requiresAdminConfirmation: false,
    enabled: true,
  },
  {
    id: "fitness_leave_coupon",
    category: "protection",
    name: "健身请假券",
    description: "当天无法健身时保护连续记录不掉线，并冻结下一次真实健身奖励档位。",
    useTiming: "today",
    effect: { type: "leave_protection", protectsStreak: true, freezesNextFitnessRewardTier: true },
    stackable: false,
    maxUsePerUserPerDay: 1,
    requiresAdminConfirmation: false,
    enabled: true,
  },
  {
    id: "luckin_coffee_coupon",
    category: "real_world",
    name: "瑞幸咖啡券",
    description: "可找管理员线下兑换一杯瑞幸咖啡。",
    useTiming: "manual_redemption",
    effect: { type: "real_world_redemption", redemptionType: "luckin_coffee" },
    stackable: true,
    requiresAdminConfirmation: true,
    enabled: true,
  },
  {
    id: "drink_water_ping",
    category: "social",
    name: "点名喝水令",
    description: "点名一位成员喝水，对方确认后生成响应记录。",
    useTiming: "instant",
    effect: { type: "social_invitation", invitationType: "DRINK_WATER" },
    stackable: true,
    maxUsePerUserPerDay: 2,
    requiresAdminConfirmation: false,
    enabled: true,
  },
  {
    id: "walk_ping",
    category: "social",
    name: "出门溜达令",
    description: "邀请一位成员起身走一圈，对方确认后生成轻动态。",
    useTiming: "instant",
    effect: { type: "social_invitation", invitationType: "WALK_AROUND" },
    stackable: true,
    maxUsePerUserPerDay: 2,
    requiresAdminConfirmation: false,
    enabled: true,
  },
  {
    id: "team_standup_ping",
    category: "social",
    name: "全员起立令",
    description: "发起一次全队起身提醒，记录当天响应人数。",
    useTiming: "instant",
    effect: { type: "social_invitation", invitationType: "TEAM_STANDUP" },
    stackable: true,
    maxUsePerTeamPerDay: 1,
    requiresAdminConfirmation: false,
    enabled: true,
  },
  {
    id: "chat_ping",
    category: "social",
    name: "今日闲聊令",
    description: "邀请一位成员完成“把事办黄”，双方完成后生成响应记录。",
    useTiming: "instant",
    effect: { type: "social_invitation", invitationType: "CHAT" },
    stackable: true,
    maxUsePerUserPerDay: 2,
    requiresAdminConfirmation: false,
    enabled: true,
  },
  {
    id: "share_info_ping",
    category: "social",
    name: "红盘情报令",
    description: "点名一位成员分享今天看到的新东西，完成后进入今日小摘要。",
    useTiming: "instant",
    effect: { type: "social_invitation", invitationType: "SHARE_INFO" },
    stackable: true,
    maxUsePerUserPerDay: 2,
    requiresAdminConfirmation: false,
    enabled: true,
  },
  {
    id: "team_broadcast_coupon",
    category: "social",
    name: "团队小喇叭",
    description: "把一句轻量播报发到团队动态或后续摘要。",
    useTiming: "instant",
    effect: { type: "social_invitation", invitationType: "TEAM_BROADCAST" },
    stackable: true,
    maxUsePerTeamPerDay: 1,
    requiresAdminConfirmation: false,
    enabled: true,
  },
];
