import type { RewardDefinition } from "./types";

export const REWARD_DEFINITIONS: RewardDefinition[] = [
  {
    id: "coins_005",
    tier: "coin",
    kind: "coins",
    rarity: "common",
    name: "摸鱼津贴",
    description: "获得 5 银子。",
    weight: 15,
    effect: { type: "grant_coins", amount: 5 },
    enabled: true,
  },
  {
    id: "coins_010",
    tier: "coin",
    kind: "coins",
    rarity: "common",
    name: "工位补贴",
    description: "获得 10 银子。",
    weight: 12,
    effect: { type: "grant_coins", amount: 10 },
    enabled: true,
  },
  {
    id: "coins_020",
    tier: "coin",
    kind: "coins",
    rarity: "common",
    name: "今日没白来",
    description: "获得 20 银子。",
    weight: 10,
    effect: { type: "grant_coins", amount: 20 },
    enabled: true,
  },
  {
    id: "coins_040",
    tier: "coin",
    kind: "coins",
    rarity: "uncommon",
    name: "老板没发现",
    description: "获得 40 银子。",
    weight: 5,
    effect: { type: "grant_coins", amount: 40 },
    enabled: true,
  },
  {
    id: "coins_080",
    tier: "coin",
    kind: "coins",
    rarity: "rare",
    name: "小发一笔",
    description: "获得 80 银子。",
    weight: 2,
    effect: { type: "grant_coins", amount: 80 },
    enabled: true,
  },
  {
    id: "coins_120",
    tier: "coin",
    kind: "coins",
    rarity: "rare",
    name: "牛马暴富",
    description: "获得 120 银子。",
    weight: 1,
    effect: { type: "grant_coins", amount: 120 },
    enabled: true,
  },
  {
    id: "reward_task_reroll",
    tier: "utility",
    kind: "inventory_item",
    rarity: "common",
    name: "任务换班券",
    description: "获得 1 张任务换班券。",
    weight: 10,
    effect: { type: "grant_item", itemId: "task_reroll_coupon", quantity: 1 },
    enabled: true,
  },
  {
    id: "reward_small_boost",
    tier: "utility",
    kind: "inventory_item",
    rarity: "uncommon",
    name: "小暴击券",
    description: "获得 1 张小暴击券。",
    weight: 9,
    effect: { type: "grant_item", itemId: "small_boost_coupon", quantity: 1 },
    enabled: true,
  },
  {
    id: "reward_fitness_leave",
    tier: "utility",
    kind: "inventory_item",
    rarity: "uncommon",
    name: "健身请假券",
    description: "获得 1 张健身请假券。",
    weight: 8,
    effect: { type: "grant_item", itemId: "fitness_leave_coupon", quantity: 1 },
    enabled: true,
  },
  {
    id: "reward_drink_water_ping",
    tier: "social",
    kind: "inventory_item",
    rarity: "common",
    name: "点名喝水令",
    description: "获得 1 张点名喝水令。",
    weight: 5,
    effect: { type: "grant_item", itemId: "drink_water_ping", quantity: 1 },
    enabled: true,
  },
  {
    id: "reward_walk_ping",
    tier: "social",
    kind: "inventory_item",
    rarity: "common",
    name: "出门溜达令",
    description: "获得 1 张出门溜达令。",
    weight: 5,
    effect: { type: "grant_item", itemId: "walk_ping", quantity: 1 },
    enabled: true,
  },
  {
    id: "reward_team_standup_ping",
    tier: "social",
    kind: "inventory_item",
    rarity: "uncommon",
    name: "全员起立令",
    description: "获得 1 张全员起立令。",
    weight: 4,
    effect: { type: "grant_item", itemId: "team_standup_ping", quantity: 1 },
    enabled: true,
  },
  {
    id: "reward_chat_ping",
    tier: "social",
    kind: "inventory_item",
    rarity: "common",
    name: "今日闲聊令",
    description: "获得 1 张今日闲聊令。",
    weight: 4,
    effect: { type: "grant_item", itemId: "chat_ping", quantity: 1 },
    enabled: true,
  },
  {
    id: "reward_share_info_ping",
    tier: "social",
    kind: "inventory_item",
    rarity: "common",
    name: "红盘情报令",
    description: "获得 1 张红盘情报令。",
    weight: 4,
    effect: { type: "grant_item", itemId: "share_info_ping", quantity: 1 },
    enabled: true,
  },
  {
    id: "reward_team_broadcast",
    tier: "social",
    kind: "inventory_item",
    rarity: "uncommon",
    name: "团队小喇叭",
    description: "获得 1 张团队小喇叭。",
    weight: 2,
    effect: { type: "grant_item", itemId: "team_broadcast_coupon", quantity: 1 },
    enabled: true,
  },
  {
    id: "reward_today_title",
    tier: "cosmetic",
    kind: "title",
    rarity: "common",
    name: "今日称号",
    description: "获得一个当天展示称号。",
    weight: 6,
    effect: { type: "grant_title", titleId: "legal_slacker" },
    enabled: false,
  },
  {
    id: "reward_double_niuma",
    tier: "rare",
    kind: "inventory_item",
    rarity: "epic",
    name: "双倍牛马券",
    description: "获得 1 张双倍牛马券。",
    weight: 2,
    effect: { type: "grant_item", itemId: "double_niuma_coupon", quantity: 1 },
    enabled: true,
  },
  {
    id: "reward_season_sprint",
    tier: "rare",
    kind: "inventory_item",
    rarity: "epic",
    name: "赛季冲刺券",
    description: "获得 1 张赛季冲刺券。",
    weight: 1,
    effect: { type: "grant_item", itemId: "season_sprint_coupon", quantity: 1 },
    enabled: true,
  },
  {
    id: "reward_luckin_coffee",
    tier: "rare",
    kind: "real_world_redemption",
    rarity: "epic",
    name: "瑞幸咖啡券",
    description: "获得 1 张瑞幸咖啡券。",
    weight: 1,
    effect: { type: "grant_real_world_redemption", itemId: "luckin_coffee_coupon", quantity: 1 },
    enabled: true,
  },
];
