import type { TaskCardDefinition } from "./types";

export const TASK_CARDS: TaskCardDefinition[] = [
  {
    id: "movement_001",
    dimensionKey: "movement",
    title: "工位重启",
    description: "离开椅子站起来 2 分钟，让身体退出省电模式。",
    completionTextOptions: ["电量+1", "已复活", "屁股离线"],
    effort: "light",
    scene: "general",
    repeatCooldownDays: 3,
    isWeekendOnly: false,
    tags: ["stand", "break"],
    weight: 1,
    enabled: true,
  },
  {
    id: "movement_002",
    dimensionKey: "movement",
    title: "屁股离线",
    description: "找一个理由离开座位走一小圈，哪怕只是去看看饮水机还在不在。",
    completionTextOptions: ["屁股离线", "带薪巡逻", "身体上线"],
    effort: "light",
    scene: "office",
    repeatCooldownDays: 3,
    isWeekendOnly: false,
    tags: ["walk", "office"],
    weight: 1,
    enabled: true,
  },
  {
    id: "movement_003",
    dimensionKey: "movement",
    title: "肩颈开机",
    description: "做 3 轮肩颈环绕，拯救一下被屏幕封印的脖子。",
    completionTextOptions: ["肩颈开机", "脖子解封", "电量回升"],
    effort: "light",
    scene: "general",
    repeatCooldownDays: 3,
    isWeekendOnly: false,
    tags: ["stretch", "neck"],
    weight: 1,
    enabled: true,
  },
  {
    id: "movement_004",
    dimensionKey: "movement",
    title: "窗边回血",
    description: "走到窗边或户外看远处 30 秒，顺便深呼吸几口。",
    completionTextOptions: ["眼睛回血", "已远眺", "精神补电"],
    effort: "light",
    scene: "general",
    repeatCooldownDays: 4,
    isWeekendOnly: false,
    tags: ["eyes", "breath"],
    weight: 1,
    enabled: true,
  },
  {
    id: "movement_005",
    dimensionKey: "movement",
    title: "腰背解冻",
    description: "双手向上伸展，再左右侧弯各 10 秒，把腰背从压缩包里解出来。",
    completionTextOptions: ["腰背解冻", "已拉伸", "身体解压"],
    effort: "light",
    scene: "general",
    repeatCooldownDays: 3,
    isWeekendOnly: false,
    tags: ["stretch", "back"],
    weight: 1,
    enabled: true,
  },
  {
    id: "hydration_001",
    dimensionKey: "hydration",
    title: "首杯投币",
    description: "喝一杯水，给今天的身体系统投个启动币。",
    completionTextOptions: ["已续杯", "水位正常", "身体开机"],
    effort: "light",
    scene: "general",
    repeatCooldownDays: 2,
    isWeekendOnly: false,
    tags: ["water"],
    weight: 1,
    enabled: true,
  },
  {
    id: "hydration_002",
    dimensionKey: "hydration",
    title: "茶水间续命",
    description: "去接一杯水，顺便完成一次合法离岗。",
    completionTextOptions: ["合法离岗", "水杯上线", "已补水"],
    effort: "light",
    scene: "office",
    repeatCooldownDays: 3,
    isWeekendOnly: false,
    tags: ["water", "office"],
    weight: 1,
    enabled: true,
  },
  {
    id: "hydration_003",
    dimensionKey: "hydration",
    title: "杯子见底",
    description: "把当前杯子里的水喝到见底，给水杯一个交代。",
    completionTextOptions: ["杯子见底", "水债已还", "不再干巴"],
    effort: "light",
    scene: "general",
    repeatCooldownDays: 2,
    isWeekendOnly: false,
    tags: ["water"],
    weight: 1,
    enabled: true,
  },
  {
    id: "hydration_004",
    dimensionKey: "hydration",
    title: "无糖信仰",
    description: "完成一次无糖补水，白水、气泡水、淡茶都算。",
    completionTextOptions: ["无糖补给", "水位正常", "清澈一点"],
    effort: "light",
    scene: "general",
    repeatCooldownDays: 3,
    isWeekendOnly: false,
    tags: ["water", "sugar_free"],
    weight: 1,
    enabled: true,
  },
  {
    id: "hydration_005",
    dimensionKey: "hydration",
    title: "咖啡债还款",
    description: "今天喝了咖啡、茶或奶茶的话，额外补一杯水。",
    completionTextOptions: ["咖啡债已还", "水分回补", "续命平衡"],
    effort: "light",
    scene: "general",
    repeatCooldownDays: 4,
    isWeekendOnly: false,
    tags: ["water", "coffee"],
    weight: 1,
    enabled: true,
  },
  {
    id: "social_001",
    dimensionKey: "social",
    title: "废话 KPI",
    description: "和同事聊两句无关工作的废话，完成今日人类连接。",
    completionTextOptions: ["废话达标", "人类连接", "班味已散"],
    effort: "light",
    scene: "office",
    repeatCooldownDays: 3,
    isWeekendOnly: false,
    tags: ["chat"],
    weight: 1,
    enabled: true,
  },
  {
    id: "social_002",
    dimensionKey: "social",
    title: "班味通风",
    description: "找人吐槽一句今天的班味来源，不点名攻击，不泄露隐私。",
    completionTextOptions: ["班味通风", "情绪排水", "吐槽完成"],
    effort: "light",
    scene: "general",
    repeatCooldownDays: 4,
    isWeekendOnly: false,
    tags: ["chat", "mood"],
    weight: 1,
    enabled: true,
  },
  {
    id: "social_003",
    dimensionKey: "social",
    title: "夸夸回血",
    description: "真诚夸一个同事一句，可以是工作、穿搭、表情包或精神状态。",
    completionTextOptions: ["夸夸回血", "善意发射", "气氛回暖"],
    effort: "light",
    scene: "office",
    repeatCooldownDays: 4,
    isWeekendOnly: false,
    tags: ["praise", "chat"],
    weight: 1,
    enabled: true,
  },
  {
    id: "social_004",
    dimensionKey: "social",
    title: "状态词上报",
    description: "在群里或私聊里发一个今天的状态词，比如“半熟”“加载中”“已掉线”。",
    completionTextOptions: ["状态已上报", "加载中", "今日冒泡"],
    effort: "light",
    scene: "general",
    repeatCooldownDays: 3,
    isWeekendOnly: false,
    tags: ["status", "chat"],
    weight: 1,
    enabled: true,
  },
  {
    id: "social_005",
    dimensionKey: "social",
    title: "辛苦了发射",
    description: "对一个人说“辛苦了”，包括同事、朋友、家人或自己。",
    completionTextOptions: ["辛苦了发射", "善意到账", "精神回血"],
    effort: "light",
    scene: "general",
    repeatCooldownDays: 3,
    isWeekendOnly: false,
    tags: ["care", "chat"],
    weight: 1,
    enabled: true,
  },
  {
    id: "learning_001",
    dimensionKey: "learning",
    title: "三分钟扫盘",
    description: "看一篇短文章、帖子或资讯，三分钟也算学习。",
    completionTextOptions: ["脑子进账", "信息补仓", "今日看红"],
    effort: "light",
    scene: "general",
    repeatCooldownDays: 3,
    isWeekendOnly: false,
    tags: ["article", "news"],
    weight: 1,
    enabled: true,
  },
  {
    id: "learning_002",
    dimensionKey: "learning",
    title: "新词解锁",
    description: "查一个今天看到但不太懂的词，别让它继续装熟。",
    completionTextOptions: ["新词解锁", "知识入账", "脑子补仓"],
    effort: "light",
    scene: "general",
    repeatCooldownDays: 4,
    isWeekendOnly: false,
    tags: ["learn", "term"],
    weight: 1,
    enabled: true,
  },
  {
    id: "learning_003",
    dimensionKey: "learning",
    title: "收藏回血包",
    description: "收藏一个有用链接、工具、文章或资料，未来的你会感谢现在的你。",
    completionTextOptions: ["链接入库", "回血包已存", "资料补仓"],
    effort: "light",
    scene: "general",
    repeatCooldownDays: 4,
    isWeekendOnly: false,
    tags: ["bookmark", "tool"],
    weight: 1,
    enabled: true,
  },
  {
    id: "learning_004",
    dimensionKey: "learning",
    title: "AI 小抄",
    description: "看一个 AI、效率工具或自动化技巧，学到一个点即可。",
    completionTextOptions: ["AI 小抄+1", "效率入账", "工具补仓"],
    effort: "light",
    scene: "general",
    repeatCooldownDays: 4,
    isWeekendOnly: false,
    tags: ["ai", "tool"],
    weight: 1,
    enabled: true,
  },
  {
    id: "learning_005",
    dimensionKey: "learning",
    title: "一句话笔记",
    description: "把今天学到的一个东西写成一句话，短到能发群里最好。",
    completionTextOptions: ["一句话入账", "脑子看红", "知识落袋"],
    effort: "medium",
    scene: "general",
    repeatCooldownDays: 4,
    isWeekendOnly: false,
    tags: ["note", "learn"],
    weight: 1,
    enabled: true,
  },
];
