import type { SupplyTaskRecordPreview } from "./types";

export const supplyTaskRecordAssetPaths = {
  profileAvatar: "/avatars/male1.png",
  avatars: {
    sailor: "/avatars/male2.png",
    deer: "/avatars/female1.png",
    runner: "/avatars/male3.png",
  },
  sidebar: {
    background: "/assets/home-scenes/supply/dashboard/dashboard-gym-bg.webp",
    hero: "/assets/home-scenes/supply/dashboard/niuma-hero-clean.webp",
  },
  rewardIcons: {
    coins: "/gamification/rewards/icons/coins_020.png",
    ticket: "/gamification/rewards/icons/task_reroll_coupon.png",
    coffee: "/gamification/rewards/icons/luckin_coffee_coupon.png",
  },
} as const;

export const supplyTaskRecordMock: SupplyTaskRecordPreview = {
  topBar: {
    resources: [
      { id: "coins", label: "银子", value: "2,450", icon: "◎" },
      { id: "ticket", label: "补给券", value: "18", icon: "券" },
      { id: "backpack", label: "背包", value: "68/120", icon: "包" },
    ],
    profile: {
      username: "Vincent",
      avatar: supplyTaskRecordAssetPaths.profileAvatar,
    },
  },
  sidebar: {
    menuItems: [
      { id: "today", label: "今日记录", icon: "▤", active: true },
      { id: "draws", label: "抽卡记录", icon: "▥", active: false },
      { id: "redemptions", label: "兑换记录", icon: "券", active: false },
      { id: "radar", label: "队友雷达", icon: "●●", active: false },
      { id: "rules", label: "规则说明", icon: "冊", active: false },
    ],
    backHref: "/ui-lab/supply-dashboard",
    mascot: {
      background: supplyTaskRecordAssetPaths.sidebar.background,
      hero: supplyTaskRecordAssetPaths.sidebar.hero,
    },
  },
  filters: [
    { id: "all", label: "全部", active: true },
    { id: "mainline", label: "主线任务", active: false },
    { id: "social", label: "社交互动", active: false },
    { id: "reward", label: "奖励领取", active: false },
    { id: "system", label: "系统通知", active: false },
  ],
  day: {
    label: "今天",
    dateLabel: "05月24日",
    weekday: "星期六",
  },
  timelineRecords: [
    {
      id: "movement-task",
      time: "08:21",
      title: "运动任务",
      subtitle: "累计步数 >= 8000 步",
      category: "mainline",
      categoryLabel: "主线任务",
      categoryTone: "green",
      icon: { type: "text", value: "👟", alt: "运动任务" },
      reward: { icon: "券", label: "生命票", amount: "x1" },
      status: "completed",
      statusLabel: "已完成",
    },
    {
      id: "hydration-task",
      time: "09:03",
      title: "喝水任务",
      subtitle: "累计饮水 >= 2000 ml",
      category: "mainline",
      categoryLabel: "主线任务",
      categoryTone: "green",
      icon: { type: "text", value: "💧", alt: "喝水任务" },
      reward: { icon: "券", label: "生命票", amount: "x1" },
      status: "completed",
      statusLabel: "已完成",
    },
    {
      id: "social-task",
      time: "10:15",
      title: "社交任务",
      subtitle: "与队友互动 >= 1 次",
      category: "social",
      categoryLabel: "主线任务",
      categoryTone: "green",
      icon: { type: "text", value: "💬", alt: "社交任务" },
      reward: { icon: "券", label: "生命票", amount: "x1" },
      status: "completed",
      statusLabel: "已完成",
    },
    {
      id: "learning-task",
      time: "11:40",
      title: "学习任务",
      subtitle: "学习时长 >= 30 分钟",
      category: "mainline",
      categoryLabel: "主线任务",
      categoryTone: "green",
      icon: { type: "text", value: "📖", alt: "学习任务" },
      reward: { icon: "券", label: "生命票", amount: "x1" },
      status: "completed",
      statusLabel: "已完成",
    },
    {
      id: "mainline-bonus",
      time: "12:02",
      title: "完成全部主线任务",
      subtitle: "",
      category: "reward",
      categoryLabel: "奖励领取",
      categoryTone: "orange",
      icon: { type: "image", value: supplyTaskRecordAssetPaths.rewardIcons.ticket, alt: "补给券" },
      reward: { icon: "券", label: "补给券", amount: "x1" },
      status: "claimed",
      statusLabel: "已领取",
    },
    {
      id: "draw-reward",
      time: "12:05",
      title: "在补给抽卡机中抽取",
      subtitle: "",
      category: "draw",
      categoryLabel: "抽卡奖励",
      categoryTone: "orange",
      icon: { type: "text", value: "🎰", alt: "抽卡奖励" },
      reward: { icon: "🧃", label: "运动饮料（R）", amount: "x1" },
      status: "claimed",
      statusLabel: "已领取",
    },
    {
      id: "streak-reward",
      time: "12:06",
      title: "连续打卡 18 天奖励",
      subtitle: "",
      category: "system",
      categoryLabel: "系统奖励",
      categoryTone: "orange",
      icon: { type: "image", value: supplyTaskRecordAssetPaths.rewardIcons.coins, alt: "牛马币" },
      reward: { icon: "◎", label: "牛马币", amount: "x100" },
      status: "claimed",
      statusLabel: "已领取",
    },
  ],
  radar: {
    tabs: [
      { id: "pending", label: "待响应 (3)", active: true },
      { id: "responded", label: "已回应", active: false },
      { id: "expired", label: "已过期", active: false },
    ],
    invites: [
      {
        id: "invite-sailor",
        avatar: supplyTaskRecordAssetPaths.avatars.sailor,
        name: "大力水手",
        message: "邀请你互动",
        timeLabel: "今天 10:20",
        statusLabel: "待响应",
      },
      {
        id: "invite-deer",
        avatar: supplyTaskRecordAssetPaths.avatars.deer,
        name: "小鹿同学",
        message: "邀请你互动",
        timeLabel: "今天 09:15",
        statusLabel: "待响应",
      },
      {
        id: "invite-runner",
        avatar: supplyTaskRecordAssetPaths.avatars.runner,
        name: "跑步阿斌",
        message: "邀请你互动",
        timeLabel: "昨天 21:47",
        statusLabel: "待响应",
      },
    ],
  },
  redemptions: {
    items: [
      {
        id: "coffee-processing",
        icon: supplyTaskRecordAssetPaths.rewardIcons.coffee,
        title: "咖啡兑换券（中杯）",
        requestedAt: "申请时间：05-24 12:10",
        secondaryLabel: "预计完成：05-24 20:00",
        status: "processing",
        statusLabel: "兑换中",
      },
      {
        id: "coffee-completed",
        icon: supplyTaskRecordAssetPaths.rewardIcons.coffee,
        title: "咖啡兑换券（中杯）",
        requestedAt: "申请时间：05-22 08:30",
        secondaryLabel: "完成时间：05-22 14:05",
        status: "completed",
        statusLabel: "已完成",
      },
      {
        id: "coffee-expired",
        icon: supplyTaskRecordAssetPaths.rewardIcons.coffee,
        title: "咖啡兑换券（中杯）",
        requestedAt: "申请时间：05-19 19:40",
        secondaryLabel: "失效时间：05-21 19:40",
        status: "expired",
        statusLabel: "已失效",
      },
    ],
  },
};
