import { supplyUiLabResources } from "@/components/gamification/ui-lab/supply-data/resources";
import type { SupplyTeamGoalPreview } from "./types";

export const supplyTeamGoalAssetPaths = {
  topbarLogo: "/assets/home-scenes/supply/shared/supply-topbar-cow-logo.png",
  media: {
    roadBackground: "/assets/home-scenes/supply/team-goal/team-goal-road-bg.webp",
    crest: "/assets/home-scenes/supply/team-goal/team-goal-crest.webp",
    vaultChest: "/assets/home-scenes/supply/team-goal/team-goal-vault-chest.webp",
  },
  fallbackLogo: "/logo.png",
  profileAvatar: "/avatars/male1.png",
  rewardIcons: {
    coins: "/gamification/rewards/icons/coins_020.png",
    ticket: "/gamification/rewards/icons/task_reroll_coupon.png",
    boost: "/gamification/rewards/icons/small_boost_coupon.png",
    teamBroadcast: "/gamification/rewards/icons/team_broadcast_coupon.png",
  },
} as const;

export const supplyTeamGoalMock: SupplyTeamGoalPreview = {
  media: supplyTeamGoalAssetPaths.media,
  topBar: {
    resources: supplyUiLabResources.dashboard,
    profile: {
      username: "Vincent",
      avatar: supplyTeamGoalAssetPaths.profileAvatar,
    },
  },
  team: {
    name: "牛马不加班",
    level: 12,
    memberCount: 28,
    memberLimit: 30,
  },
  season: {
    label: "赛季目标 S3",
    goalName: "牛马不加班",
    dateRange: "05.20 - 06.16",
    remainingDays: 18,
    currentPoints: 78560,
    targetPoints: 120000,
    progressPercent: 65,
    currentStage: 3,
    totalStages: 5,
  },
  vault: {
    amount: 5680,
    helper: "通过团队目标获得",
  },
  seasonRewards: [
    { id: "team-exp", icon: "EXP", label: "团队经验", value: "+30%" },
    { id: "ticket-boost", icon: "券", label: "抽奖券获取", value: "+20%" },
    { id: "team-title", icon: "盾", label: "团队称号", value: "全力以赴" },
    { id: "avatar-frame", icon: "框", label: "专属头像框", value: "30天" },
  ],
  completionReward: {
    title: "赛季达成奖励",
    memberRewards: ["银子 x100", "抽奖券 x3"],
    teamReward: "团队称号 30天",
    reportReward: "赛季达成高光",
  },
  milestones: [
    { id: "start", order: 1, title: "启程之路", targetPoints: 20000, status: "completed", rewardLabel: "已完成" },
    { id: "front", order: 2, title: "并肩前行", targetPoints: 50000, status: "completed", rewardLabel: "已完成" },
    { id: "all-in", order: 3, title: "全力以赴", targetPoints: 80000, status: "current", rewardLabel: "当前阶段" },
    { id: "limit", order: 4, title: "突破极限", targetPoints: 100000, status: "active", rewardLabel: "进行中" },
    { id: "glory", order: 5, title: "荣耀时刻", targetPoints: 120000, status: "locked", rewardLabel: "未解锁" },
  ],
  milestoneRewards: [
    { percent: 20, title: "公告点亮", rewardLabel: "团队公告高光", status: "completed" },
    { percent: 40, title: "全员小补给", rewardLabel: "每人 抽奖券 x1", status: "completed" },
    { percent: 65, title: "称号预览", rewardLabel: "团队称号预览", status: "current" },
    { percent: 85, title: "银子加班费", rewardLabel: "每人 银子 x50", status: "active" },
    { percent: 100, title: "赛季达成", rewardLabel: "触发赛季达成奖励", status: "locked" },
  ],
  tasks: [
    {
      id: "team-workout",
      icon: "👟",
      title: "全队运动打卡",
      subtitle: "全队累计运动打卡",
      metricSource: "今日有效健身打卡人数",
      current: 20,
      target: 30,
      unit: "人",
      reward: { icon: "EXP", label: "团队经验", value: "+100" },
      status: "active",
    },
    {
      id: "four-dimension",
      icon: "📖",
      title: "四维任务完成",
      subtitle: "运动/喝水/社交/学习任务",
      metricSource: "今日四维任务完成份数",
      current: 28,
      target: 40,
      unit: "份",
      reward: { icon: "券", label: "抽奖券", value: "+2" },
      status: "active",
    },
    {
      id: "social-response",
      icon: "💬",
      title: "社交互动响应",
      subtitle: "回复队友互动消息",
      metricSource: "今日弱社交已回应次数",
      current: 12,
      target: 15,
      unit: "次",
      reward: { icon: "EXP", label: "团队经验", value: "+80" },
      status: "active",
    },
    {
      id: "draw-usage",
      icon: "🎟",
      title: "全队抽卡活跃",
      subtitle: "全队消耗抽奖券抽卡",
      metricSource: "今日全队抽卡次数",
      current: 18,
      target: 25,
      unit: "次",
      reward: { icon: "券", label: "抽奖券", value: "+2" },
      status: "active",
    },
  ],
  rewardPreview: [
    {
      id: "team-chest",
      title: "团队宝箱",
      subtitle: "达成后解锁丰厚随机奖励",
      image: supplyTeamGoalAssetPaths.media.vaultChest,
      icon: "🎁",
      tone: "purple",
    },
    {
      id: "team-boost",
      title: "团队加成（7天）",
      subtitle: "经验 +30% / 抽奖券 +20%",
      image: null,
      icon: "EXP",
      tone: "orange",
    },
    {
      id: "team-title",
      title: "团队称号",
      subtitle: "团队专属称号 30天",
      image: null,
      icon: "全力以赴",
      tone: "blue",
    },
    {
      id: "weekly-highlight",
      title: "周报高光",
      subtitle: "赛季达成高光展示专属时刻",
      image: null,
      icon: "📈",
      tone: "violet",
    },
  ],
  announcement: {
    message: "团队公告：周六早上 8 点公园团练，记得来哦！💪",
  },
};
